
language: android
android:
  components:
    - build-tools-20.0.0
    - android-L
    - sys-img-x86-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  script:  "./gradlew build"
  - ./gradlew assembleDebug
   - echo "nexusUsername=dummy" >> library/gradle.properties
  - echo "nexusPassword=dummy" >> library/gradle.properties
  - ./gradlew clean assemble check
  - ./gradlew :library:androidJavadocs
  
before_script:
  
  - adb shell input keyevent 82 &