@startuml
: Utilisateur: as Utilisateur


Utilisateur -up->(Rechercher un service )
Utilisateur -down-> (Sélectionner un livre par une discipline )
Utilisateur -right-> (Rechercher une cote )
Utilisateur -right->(Sélectionner un livre par une racine de cote )
(Sélectionner un livre par sous-discipline) .> (Sélectionner un livre par une discipline ) : extends




@enduml