@startuml


@startuml

Utilisateur "0..*" -- "1..*" Map : consulter

 Salle"1..6"-- "1"Map : rechercher
Salle "1"*-- "1..*" Etagére
 Discipline"1..*"--* "1..*" Etagére

Discipline "1"*-- "1..*"  SousDiscipline
SousDiscipline"1..*"*-- "1..*" Livre
Livre *--  Cote
Cote *--  RacineDeCote

class Map{
nomMap:String
plan:Map

}
class Salle {
nomSalle:String
niveau:Int
}

class Etagére{
numEtagere:Int
}

class Discipline{
nomDisc:String
}

class SousDiscipline{
nomSousDisc:String
}

class Livre {
titre:String
auteur:String
}

class Cote {
numCote:Int
}

class RacineDeCote{
indiceCote:Int
}

@enduml
